name: Next Blog CI and Deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: crpi-nn9nq55uadvw3j9x.cn-chengdu.personal.cr.aliyuncs.com
  NAMESPACE: rauxo
  REPOSITORY: wjun-blog-next

jobs:
  # =========================
  # 1️⃣ 构建并推送镜像
  # =========================
  docker:
    runs-on: ubuntu-latest

    steps:
      # 拉代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录 ACR
      - name: Login to ACR
        run: |
          docker login \
            --username=${{ secrets.ACR_USERNAME }} \
            --password=${{ secrets.ACR_PASSWORD }} \
            $REGISTRY

      # 构建镜像（只用 latest）
      - name: Build Docker Image
        run: |
          docker build \
            -t $REGISTRY/$NAMESPACE/$REPOSITORY:latest \
            .

      # 推送镜像
      - name: Push Docker Image
        run: |
          docker push $REGISTRY/$NAMESPACE/$REPOSITORY:latest

  # =========================
  # 2️⃣ 部署服务器
  # =========================
  deploy:
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -i private_key.pem -o StrictHostKeyChecking=no root@47.109.69.204 << 'EOF'

            set -e

            echo "🚀 Start deploying latest version"

            REGISTRY="crpi-nn9nq55uadvw3j9x.cn-chengdu.personal.cr.aliyuncs.com"

            echo "${{ secrets.ACR_PASSWORD }}" | docker login \
              --username="${{ secrets.ACR_USERNAME }}" \
              --password-stdin \
              "$REGISTRY"

            echo "docker login success"

            cd /srv/docker-app

            echo "Pulling latest image..."

            # 拉最新镜像
            docker compose pull wjun-blog-next

            echo "Latest image pulled"

            # 重启服务
            docker compose up -d wjun-blog-next

            # 清理旧镜像
            docker image prune -af

            echo "✅ Deploy success"

          EOF